### PR TITLE
feat(db): Allow loading DbOptions from a configuration file or environment variables

### LINKED ISSUE #263: Make `DbConfig` serializable
We're slowly encoding all of the `DbConfig` options as Clap arguments in `bencher`. It might be nice to support `DbConfig` serialization from a file instead. @agavra mentioned `.properties` files. I had been thinking of JSON/YAML/TOML encoding. Regardless of the format, something like that would be handy.

(Originally brought up in #261.)

### PR DESCRIPTION
**Pull request by calavera**
This change adds these functions to allow loading DbOptions from configuration files or environment variables:

`from_file`: loads the options from a specific file.
`from_env`: loads the options from environment variables with a specific prefix.
`load`: loads the options with some default file locations and `SLATEDB_` as a default prefix. This option is accumulative. If a config file exists, and environment variables also exist, both are combined. Environment variables override settings in the configuration file.

I was going to document all this and provide additional configuration examples, but I could not find a good place to do it. Let me know where I should add that @criccomini. If this repo doesn't include the documentation, I'll be happy to open a new PR in a different repository for the documentation.

PS: Most of the changes are in `src/config.rs` which GitHub collapses 🤷 

Fixes #263

### CODE REVIEW

**Comment by criccomini** [comment]
> I was going to document all this and provide additional configuration examples, but I could not find a good place to do it. Let me know where I should add that @criccomini. If this repo doesn't include the documentation, I'll be happy to open a new PR in a different repository for the documentation.

I think the best place for this is on [slatedb.io](https://slatedb.io). A PR at https://github.com/slatedb/slatedb-website would be great. 🙏

**Comment by criccomini** [comment]
Just took a look at the website, and I realized that I removed the config docs on the site and link directly to `DbOptions` docs.rs now. So perhaps `DbOptions`'s module docs are the best place to put it.

**Review by criccomini — APPROVED** [review]
This is awesome! Thank you so much for submitting this. Really a huge help.

I'll let it sit for a day to give you a chance to add docs. I'll merge after 24h either way. :)

**Comment by calavera** [comment]
@criccomini I've added that documentation to the top of the module. I think this is ready to merge now.

**Review by criccomini — APPROVED** [review]

**Pull request merged**
